export const agentDescription = `
You are a professional teacher with expertise in IT, AI, programming, and related fields. 
Your job is to help me learn about a selected topic by guiding me through interactive learning. 
You will present me with one question at a time—this could be a quiz, logic test, coding challenge, or any other appropriate format. 
After I answer, give me detailed feedback: explain what I did right or wrong, and provide all the information I need to understand the concept fully. 
The topic will be:
`;

export const testList = [
  // PHP
  "PHP Classes and Objects",
  "Core PHP Concepts",
  "PHP Exception Handling",
  "PHP File Handling",
  "PHP Database Connectivity",
  "PHP Design Patterns",
  "PHP Sessions and Cookies",
  "Built-in PHP Functions with Code Examples",
  "PHP MySQL CRUD Operations",
  "PHP HTTP Methods with Examples",
  "PHP File Handling Functions with Code Examples",
  "PHP Scripts for Practice with Code Examples",
  "PHP Coding Challenges with Code Examples",
  "PHP Documentation and Best Practices",
  "PHP Debugging Techniques",

  // Algorithms
  "Algorithm Time and Space Complexity",
  "Big O Notation",
  "Analyzing Algorithms for Efficiency and Scalability",
  "Data Structures: Arrays, Linked Lists, Stacks, Queues, Trees, Graphs, Hash Tables",
  "Operations and Characteristics of Data Structures",
  "Linear Search and Binary Search",
  "Search Algorithms: Time Complexity and Use Cases",
  "Sorting Algorithms: Bubble Sort, Selection Sort, Insertion Sort, Merge Sort, Quick Sort, Heap Sort",
  "Sorting Algorithm Performance and Use Cases",
  "Graph Traversal Algorithms: BFS and DFS",
  "Shortest Path Algorithms: Dijkstra's and Bellman-Ford",
  "Minimum Spanning Tree Algorithms: Prim's and Kruskal's",
  "Dynamic Programming Concepts and Techniques",
  "Optimal Substructure and Overlapping Subproblems",
  "Greedy Algorithms and Their Applications",
  "Analyzing Greedy Algorithm Correctness and Optimality",
  "Divide-and-Conquer Strategy and Applications",
  "Divide-and-Conquer Examples: Binary Search, Merge Sort, Closest Pair of Points",
  "Implementing Algorithms from Scratch in PHP",
  "Translating Pseudocode into Executable Code",
  "Key Properties of Data Structures and Algorithms",
  "Algorithm Paradigms and Basic Principles",
  "Edge Cases and Special Cases in Algorithms",
  "Pseudocode and Implementation of Important Algorithms",
  "Code Review for Time and Space Complexity",
  "Flash Cards for Big O Notation and Associated Algorithms",
  "Relationships Between Data Elements: Hierarchical, Sequential, Graph-Based",
  "Common Data Structures: Arrays, Stack, Queue, Set, Object, Map, Tree, Graph",
  "Recursion",
  "Indexes and References",

  // SQL
  "Structure of SQL Queries",
  "SQL Clauses",
  "Database Normalization (1NF, 2NF, 3NF) and Denormalization",
  "Primary Keys, Foreign Keys, and Table Relationships",
  "Data Manipulation (CRUD Operations)",
  "SQL Data Transformation Using Functions",
  "SELECT Queries on Single and Multiple Tables",
  "SQL Joins for Combining Tables",
  "SQL Aggregate Functions",
  "SQL Subqueries and Nested Queries",
  "Performance Considerations of Subqueries",
  "DDL Statements for Schema Management",
  "DDL Constraints (e.g., NOT NULL, UNIQUE, CHECK)",
  "DCL Statements for Security and Permissions",
  "SQL Syntax Rules, Keywords, Naming Conventions, and Efficient Query Writing",
  "SQL Database Administration Tasks",
  "SQL Code Review and Best Practices",
  "SQL Query Tuning and Optimization Techniques (Indexing, Execution Plans)",

  // MongoDB
  "Understanding MongoDB Document Structure (JSON-like Documents)",
  "MongoDB Collections vs SQL Tables",
  "Basic CRUD Operations in MongoDB",
  "MongoDB Query Syntax and Filtering Documents",
  "Using Projection to Return Specific Fields",
  "Understanding ObjectId and _id Field",
  "Working with Embedded Documents and Arrays",
  "MongoDB Operators ($gt, $lt, $in, $and, $or, $regex, etc.)",
  "Updating Documents with $set, $unset, $push, $pull, $inc",
  "Deleting Documents and Collections",
  "Sorting, Limiting, and Skipping Results",
  "Creating and Managing Indexes in MongoDB",
  "Understanding MongoDB Aggregation Pipeline",
  "Common Aggregation Operators ($match, $group, $sort, $project, $lookup)",
  "Data Modeling in MongoDB (Embedded vs Referenced)",
  "Schema Design Best Practices in NoSQL",
  "Relationships in MongoDB (Manual References vs $lookup Joins)",
  "Working with MongoDB Compass: UI Overview and Basic Operations",
  "Running and Visualizing Aggregation Pipelines in Compass",
  "Filtering and Searching Data with Compass",
  "Creating Indexes in MongoDB Compass",
  "Importing and Exporting Data in Compass",
  "Monitoring and Analyzing Query Performance with Compass",
  "MongoDB User Roles and Authentication",
  "Working with MongoDB Databases and Collections in Compass",
  "Understanding MongoDB Transactions (Replica Set Required)",
  "Understanding BSON Data Types (Date, ObjectId, etc.)",
  "Error Handling and Validation in MongoDB",
  "Data Import/Export Using MongoDB Tools (mongoimport, mongoexport)",
  "Backup and Restore Strategies for MongoDB",
  "Query Optimization and Explain Plans in MongoDB",

  // Javascript
  "JavaScript",
  "Basic Syntax and Structure",
  "Functions",
  "Objects and Arrays",
  "Asynchronous JavaScript",
  "DOM Manipulation",
  "Error Handling",
  "ES6+ Features",
  "Array Destructuring",
  "Commonly Used Array and Object Methods",
  "Event Handling Methods and Their Use",
  "Scoping Rules: var vs let vs const",
  "Common Built-in Functions and Their Use",
  "Write Functions for Tasks: String Manipulation, Mathematical Calculations, etc.",
  "Use Higher-Order Functions and Callbacks",
  "Create a Program Using Callbacks, Promises, and Async/Await",
  "Manipulate Objects and Arrays Using Methods",
  "Functional Programming Concepts: Pure Functions, Immutability",
  "Advanced DOM Manipulation: Virtual DOM, Shadow DOM",
  "Build Tools and Task Runners: Webpack, Gulp",
  "JavaScript Frameworks and Libraries: React, Angular, Vue",
  "TypeScript for Static Typing in JavaScript",
  "Node.js for Server-Side JavaScript",

  //Typescript
  "Basic TypeScript Syntax and Structure",
  "Type Annotations and Type Inference",
  "Interfaces and Custom Types",
  "Classes and Inheritance",
  "Generics in Functions, Interfaces, and Classes",
  "Advanced Types: Union, Intersection, Tuples, etc.",
  "Modules and Namespaces",
  "JavaScript Interoperability",
  "Using TypeScript with React, Angular, or Vue",
  "TypeScript Configuration and Compiler Options",
  "Error Handling and Type Assertions",
  "Utility Types: Partial, Readonly, Record, etc.",
  "Decorators for Classes, Methods, and Properties",
  "Using TypeScript with Node.js",
  "Asynchronous Programming: Promises, Async/Await",
  "Testing TypeScript Code with Jest or Mocha",
  "Type Guards and Type Narrowing",
  "Advanced Generics: Conditional and Mapped Types",

  // Angular
  "Angular Components and Templates",
  "Angular Modules and NgModules",
  "Data Binding in Angular",
  "Angular Directives (Structural and Attribute)",
  "Angular Services and Dependency Injection",
  "Routing and Navigation in Angular",
  "Angular Forms (Template-driven and Reactive)",
  "Angular Pipes and Custom Pipes",
  "Angular Lifecycle Hooks",
  "Angular HTTP Client and Observables",
  "Angular Routing Guards and Resolvers",
  "Angular State Management with NgRx",
  "Angular Animations",
  "Angular Testing with Jasmine and Karma",
  "Angular CLI and Project Structure",
  "Angular Performance Optimization",
  "Angular Internationalization (i18n)",
  "Angular Security Best Practices",
  "Angular Lazy Loading and Module Splitting",
  "Angular Custom Validators",

  // Git
  "General Git Concepts",
  "Version Control Basics",
  "Git Architecture",
  "Key Git Terminology",
  "Branching and Merging",
  "Remote Repositories",
  "Git Workflows",
  "Essential Git Commands",

  // React
  "React JSX and TSX",
  "React Components and Props",
  "React State and Lifecycle",
  "React Handling Events",
  "React Lists and Keys",
  "React Forms",
  "React Routes",
  "React Managing State with Hooks",
  "React Context",
  "React JSX Syntax and Conventions",
  "React Redux Integration",
  "React Testing",
  "Rules and Best Practices for Managing Component State",
  "Common Event Handling Patterns in React",
  "Best Practices for Using Keys in Lists for Efficient Rendering",
  "React Asynchronous Programming",

  // //Node.js
  "Basic setup and structure of a Node.js application",
  "Node.js modules and differences between require and import",
  "Node.js File System (fs) module",
  "Creating and handling HTTP requests with Node.js HTTP module",
  "Using Event Emitter in Node.js",
  "Asynchronous programming in Node.js",
  "Using streams in Node.js",
  "Using buffers in Node.js",
  "Building web applications with Express.js",
  "Using middleware in Express.js",
  "Routing in Express.js",
  "Error handling in Node.js",
  "Integrating databases with Node.js",
  "Implementing authentication and authorization in Node.js",
  "Building RESTful APIs with Node.js and Express.js",
  "Real-time communication with Socket.io in Node.js",
  "Node.js security best practices",
  "Unit testing in Node.js",
  "Performance optimization in Node.js",
  "Deploying Node.js applications",
  "Using TypeScript with Node.js",
  "Using streams and pipelines in Node.js",
  "Node.js event loop and asynchronous programming",
  "Building CLI tools with Node.js",

  // //Express.js
  "Basics of setting up an Express.js application",
  "Express.js routing",
  "Middleware in Express.js",
  "Error handling in Express.js",
  "Using Express.js with templating engines",
  "Express.js static file serving",
  "Express.js and forms",
  "Express.js and databases",
  "Creating RESTful APIs with Express.js",
  "Securing Express.js applications",
  "Session management in Express.js",
  "Using Express.js with WebSockets for real-time communication",
  "Deploying Express.js applications",
  "Versioning and maintaining RESTful APIs in Express.js",
  "Using Express.js with TypeScript",
  "File uploads in Express.js",
  "Optimizing Express.js performance",
  "Using GraphQL with Express.js",
  "Express.js logging and debugging",
  "Customizing Express.js configurations",
];
